In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy
import sklearn

In [6]:
df = pd.read_excel("../data/dataset.xlsx")

In [7]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [8]:
df.columns.to_list()

['CustomerID',
 'Count',
 'Country',
 'State',
 'City',
 'Zip Code',
 'Lat Long',
 'Latitude',
 'Longitude',
 'Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Tenure Months',
 'Phone Service',
 'Multiple Lines',
 'Internet Service',
 'Online Security',
 'Online Backup',
 'Device Protection',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Monthly Charges',
 'Total Charges',
 'Churn Label',
 'Churn Value',
 'Churn Score',
 'CLTV',
 'Churn Reason']

In [9]:
df = df.drop(columns= ['CustomerID','Count','Lat Long','Latitude','Longitude'])

In [10]:
df.columns.to_list()

['Country',
 'State',
 'City',
 'Zip Code',
 'Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Tenure Months',
 'Phone Service',
 'Multiple Lines',
 'Internet Service',
 'Online Security',
 'Online Backup',
 'Device Protection',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Monthly Charges',
 'Total Charges',
 'Churn Label',
 'Churn Value',
 'Churn Score',
 'CLTV',
 'Churn Reason']

In [11]:
df.isnull().sum()

Country                 0
State                   0
City                    0
Zip Code                0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [12]:
df = df.drop(columns = ["Churn Reason"])

In [13]:
df.describe()

,Zip Code,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,93521.964646,32.371149,64.761692,0.265370,58.699418,4400.295755
std,1865.794555,24.559481,30.090047,0.441561,21.525131,1183.057152
min,90001.000000,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,92102.000000,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,93552.000000,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,95351.000000,55.000000,89.850000,1.000000,75.000000,5380.500000
max,96161.000000,72.000000,118.750000,1.000000,100.000000,6500.000000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country            7043 non-null   object
 1   State              7043 non-null   object
 2   City               7043 non-null   object
 3   Zip Code           7043 non-null   int64
 4   Gender             7043 non-null   object
 5   Senior Citizen     7043 non-null   object
 6   Partner            7043 non-null   object
 7   Dependents         7043 non-null   object
 8   Tenure Months      7043 non-null   int64
 9   Phone Service      7043 non-null   object
 10  Multiple Lines     7043 non-null   object
 11  Internet Service   7043 non-null   object
 12  Online Security    7043 non-null   object
 13  Online Backup      7043 non-null   object
 14  Device Protection  7043 non-null   object
 15  Tech Support       7043 non-null   object
 16  Streaming TV       7043 non-null   object
 17  Streaming Movies   7043 non-null   object
 18  Contract           7043 non-null   object
 19  Paperless Billing  7043 non-null   object
 20  Payment Method     7043 non-null   object
 21  Monthly Charges    7043 non-null   float64
 22  Total Charges      7043 non-null   object
 23  Churn Label        7043 non-null   object
 24  Churn Value        7043 non-null   int64
 25  Churn Score        7043 non-null   int64
 26  CLTV               7043 non-null   int64
dtypes: float64(1), int64(5), object(21)
memory usage: 1.5+ MB

In [15]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns.drop("Churn Value")

In [16]:
num_cols

Index(['Zip Code', 'Tenure Months', 'Monthly Charges', 'Churn Score', 'CLTV'], dtype='object')

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_df = scaler.fit_transform(df[num_cols])

In [18]:
cat_cols = df.select_dtypes(include=['object', 'category']).columns

In [19]:
df[cat_cols] = df[cat_cols].fillna("Missing").astype(str)

In [20]:
cat_cols

Index(['Country', 'State', 'City', 'Gender', 'Senior Citizen', 'Partner',
       'Dependents', 'Phone Service', 'Multiple Lines', 'Internet Service',
       'Online Security', 'Online Backup', 'Device Protection', 'Tech Support',
       'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing',
       'Payment Method', 'Total Charges', 'Churn Label'],
      dtype='object')

In [21]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoded_df = encoder.fit_transform(df[cat_cols])

In [22]:
print(encoded_df)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 147903 stored elements and shape (7043, 7707)>
  Coords	Values
  (0, 0)	1.0
  (0, 1)	1.0
  (0, 564)	1.0
  (0, 1132)	1.0
  (0, 1133)	1.0
  (0, 1135)	1.0
  (0, 1137)	1.0
  (0, 1140)	1.0
  (0, 1141)	1.0
  (0, 1144)	1.0
  (0, 1149)	1.0
  (0, 1152)	1.0
  (0, 1153)	1.0
  (0, 1156)	1.0
  (0, 1159)	1.0
  (0, 1162)	1.0
  (0, 1165)	1.0
  (0, 1169)	1.0
  (0, 1173)	1.0
  (0, 1331)	1.0
  (0, 7706)	1.0
  (1, 0)	1.0
  (1, 1)	1.0
  (1, 564)	1.0
  (1, 1131)	1.0
  :	:
  (7041, 1169)	1.0
  (7041, 1172)	1.0
  (7041, 4168)	1.0
  (7041, 7705)	1.0
  (7042, 0)	1.0
  (7042, 1)	1.0
  (7042, 34)	1.0
  (7042, 1132)	1.0
  (7042, 1133)	1.0
  (7042, 1135)	1.0
  (7042, 1137)	1.0
  (7042, 1140)	1.0
  (7042, 1141)	1.0
  (7042, 1145)	1.0
  (7042, 1149)	1.0
  (7042, 1150)	1.0
  (7042, 1155)	1.0
  (7042, 1158)	1.0
  (7042, 1161)	1.0
  (7042, 1164)	1.0
  (7042, 1167)	1.0
  (7042, 1169)	1.0
  (7042, 1170)	1.0
  (7042, 6581)	1.0
  (7042, 7705)	1.0

In [23]:
X_cat = pd.DataFrame(encoded_df)

In [24]:
X_num = pd.DataFrame(scaled_df)

In [25]:
X = pd.concat([X_num, X_cat], axis=1)

In [26]:
# Drop any column that's object type
X = X.select_dtypes(exclude=['object'])

In [27]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       7043 non-null   float64
 1   1       7043 non-null   float64
 2   2       7043 non-null   float64
 3   3       7043 non-null   float64
 4   4       7043 non-null   float64
dtypes: float64(5)
memory usage: 275.2 KB

In [28]:
y = df["Churn Value"]

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [30]:
print(f"X shape: {X.shape}")  # Should be (7043, n_features)
print(f"y shape: {y.shape}")  # Should be (7043,)

X shape: (7043, 5)
y shape: (7043,)

In [31]:
print(f"X index length: {len(X.index)}")
print(f"y index length: {len(y.index)}")

X index length: 7043
y index length: 7043

In [32]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state = 42)

In [33]:
myModel = LogisticRegression()  

myModel.fit(X_train, y_train)

LogisticRegression()

In [34]:
y_pred = myModel.predict(X_test)

In [35]:
from sklearn import datasets, linear_model, metrics
print(f"Logistic Regression model accuracy: {metrics.accuracy_score(y_test, y_pred) * 100:.2f}%")

Logistic Regression model accuracy: 88.86%